#!/usr/bin/env ruby

require 'net/http'
require 'uri'

unless system("which bundle")
  puts "First, you need to install bundler!"
  puts "=> gem install bundler"
  exit(1)
end

re = /.*http:\/\/([^\/]*)\/([^\/]*).*/
m = re.match `git remote show -n origin | grep 'Fetch URL'`

host = m[1]
uid = m[2]

uri = URI.parse "http://#{ host }/faye"
uri.port = 9292

res = Net::HTTP.post_form uri, :message => "{\"channel\":\"/#{ uid }/startup\", \"data\":\"true\"}"

puts "Starting Tutor..."
puts "Open http://#{ host }/#{ uid }/pset1 in your browser to get your learning on!"

gem_home = File.expand_path('../.lambda/vendor/bundle/ruby/1.9.1', File.dirname(__FILE__))

`cd .lambda && GEM_HOME=#{ gem_home } ruby boot.rb`

#loop do
#  sleep 5
#end

