#!/usr/bin/env ruby

require 'net/http'
require 'uri'

re = /.*http:\/\/([^\/]*)\/([^\/]*).*/
m = re.match `git remote show origin | grep 'Fetch URL'`

host = m[1]
uid = m[2]

uri = URI.parse "http://#{ host }/faye"
http = Net::HTTP.new uri.host, 9292

request = Net::HTTP::Post.new uri.require_uri
request.set_form_data :message => { :channel => "#{ uid }/startup", :data => true }

response = http.request request

puts "Starting Tutor..."

loop do
  sleep 5
end

